# Generated by Django 3.2.3 on 2021-06-01 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_rename_permit_no_vehiclegeneralform_permit_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OtherDetails',
        ),
        migrations.DeleteModel(
            name='StatutoryDetails',
        ),
        migrations.AddField(
            model_name='vehiclegeneralform',
            name='fitness',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vehiclegeneralform',
            name='fitness_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiclegeneralform',
            name='insurance',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vehiclegeneralform',
            name='insurance_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiclegeneralform',
            name='onn_vehicle',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiclegeneralform',
            name='onwer_address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehiclegeneralform',
            name='onwer_contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vehiclegeneralform',
            name='permit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vehiclegeneralform',
            name='permit_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiclegeneralform',
            name='pollution',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vehiclegeneralform',
            name='pollution_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiclegeneralform',
            name='road_tax',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vehiclegeneralform',
            name='road_tax_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiclegeneralform',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vehiclegeneralform',
            name='status_change_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiclegeneralform',
            name='vehicle_onwer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
