# Generated by Django 3.2.3 on 2021-06-01 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_auto_20210601_2325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclegeneralform',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='vehiclegeneralform',
            name='onn_vehicle',
        ),
    ]
