# Generated by Django 3.2.3 on 2021-06-01 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_auto_20210601_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclegeneralform',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiclegeneralform',
            name='onn_vehicle',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
